version: '3.5'
services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    container_name: blood_bridge_nginx
    volumes:
      - ./code:/var/www/html
    ports:
      - '80:80'

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: blood_bridge_php
    volumes:
      - ./code:/var/www/html

  mysql:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    container_name: blood_bridge_mysql
    volumes:
      - ./database:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=1620
      - MYSQL_DATABASE=bloodbridge_db
    ports:
      - '3306:3306'